version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=gogodb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"

  gogo:
    image: gogo:latest
    container_name: gogobackend
    environment:
      - 'CODE=test'
      - 'PAGINATION_MAX_SIZE=50'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - postgres
